
gist_accounting_cdj_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:CDJ:index }

gist_accounting_cdj_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:CDJ:grid }

gist_accounting_cdj_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:CDJ:addForm }

gist_accounting_cdj_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:CDJ:addSubmit }
