#BANK ACCOUNT
gist_accounting_bank_accounts_index:
    pattern: /bank_accounts
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:BankAccount:index }

gist_accounting_bank_accounts_add_form:
    pattern: /bank_account
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:BankAccount:addForm }

gist_accounting_bank_accounts_add_submit:
    pattern: /bank_account
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:BankAccount:addSubmit }

gist_accounting_bank_accounts_edit_form:
    pattern: /bank_account/{id}
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:BankAccount:editForm }

gist_accounting_bank_accounts_edit_submit:
    pattern: /bank_account/{id}
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:BankAccount:editSubmit }

gist_accounting_bank_accounts_delete:
    pattern: /bank_account/{id}/delete
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:BankAccount:delete }

gist_accounting_bank_accounts_grid:
    pattern: /bank_accounts/grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:BankAccount:grid }


#BANKS
gist_accounting_banks_index:
    pattern: /banks
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Bank:index }

gist_accounting_banks_add_form:
    pattern: /bank
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Bank:addForm }

gist_accounting_banks_add_submit:
    pattern: /bank
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:Bank:addSubmit }

gist_accounting_banks_edit_form:
    pattern: /bank/{id}
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Bank:editForm }

gist_accounting_banks_edit_submit:
    pattern: /bank/{id}
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:Bank:editSubmit }

gist_accounting_banks_delete:
    pattern: /bank/{id}/delete
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Bank:delete }

gist_accounting_banks_grid:
    pattern: /banks/grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Bank:grid }


#TERMINAL
gist_terminals_terminal_index:
    pattern: /terminals
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Terminal:index }

gist_terminals_terminal_add_form:
    pattern: /terminal
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Terminal:addForm }

gist_terminals_terminal_add_submit:
    pattern: /terminal
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:Terminal:addSubmit }

gist_terminals_terminal_edit_form:
    pattern: /terminal/{id}
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Terminal:editForm }

gist_terminals_terminal_edit_submit:
    pattern: /terminal/{id}
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:Terminal:editSubmit }

gist_terminals_terminal_delete:
    pattern: /terminal/{id}/delete
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Terminal:delete }

gist_terminals_terminal_grid:
    pattern: /terminals/grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:Terminal:grid }


#TERMINAL OPERATOR
gist_terminals_terminal_operator_index:
    pattern: /terminal_operators
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:index }

gist_terminals_terminal_operator_add_form:
    pattern: /terminal_operator
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:addForm }

gist_terminals_terminal_operator_add_submit:
    pattern: /terminal_operator
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:addSubmit }

gist_terminals_terminal_operator_edit_form:
    pattern: /terminal_operator/{id}
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:editForm }

gist_terminals_terminal_operator_edit_submit:
    pattern: /terminal_operator/{id}
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:editSubmit }

gist_terminals_terminal_operator_delete:
    pattern: /terminal_operator/{id}/delete
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:delete }

gist_terminals_terminal_operator_grid:
    pattern: /terminal_operators/grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:TerminalOperator:grid }


gist_accounting_main:
    resource: "@GistAccountingBundle/Resources/config/routing_main.yml"
    prefix:   /main

gist_accounting_accounts:
    resource: "@GistAccountingBundle/Resources/config/routing_coa.yml"
    prefix:   /coa

gist_accounting_voucher:
    resource: "@GistAccountingBundle/Resources/config/routing_voucher.yml"
    prefix:   /voucher

gist_accounting_cdj:
    resource: "@GistAccountingBundle/Resources/config/routing_cdj.yml"
    prefix:   /cdj
gist_accounting_crj:
    resource: "@GistAccountingBundle/Resources/config/routing_crj.yml"
    prefix:   /crj
gist_accounting_gj:
    resource: "@GistAccountingBundle/Resources/config/routing_general.yml"
    prefix:   /general
gist_accounting_tb:
    resource: "@GistAccountingBundle/Resources/config/routing_tb.yml"
    prefix:   /trial
gist_month_end:
    resource: "@GistAccountingBundle/Resources/config/routing_month_end.yml"
    prefix:   /month_end
gist_accounting_bs:
    resource: "@GistAccountingBundle/Resources/config/routing_bs.yml"
    prefix:   /balance_sheet
gist_accounting_pl:
    resource: "@GistAccountingBundle/Resources/config/routing_pl.yml"
    prefix:   /profit_loss