
gist_accounting_general_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:GeneralJournal:index }

gist_accounting_general_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:GeneralJournal:grid }

gist_accounting_general_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:GeneralJournal:addForm }

gist_accounting_general_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:GeneralJournal:addSubmit }
