<?php

namespace Proxies\__CG__\Hris\RecruitmentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Application extends \Hris\RecruitmentBundle\Entity\Application implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'benefits', 'profile', 'experience', 'skills', 'reference', 'exam', 'interview', 'education', 'information', 'application_checklist', 'choice', 'first_name', 'middle_name', 'last_name', 'display_name', 'nickname', 'app_status', 'email', 'offer_data', 'background_data', 'signing_data', 'appeared', 'resume', 'id', 'date_create', 'user_create', 'upload'];
        }

        return ['__isInitialized__', 'benefits', 'profile', 'experience', 'skills', 'reference', 'exam', 'interview', 'education', 'information', 'application_checklist', 'choice', 'first_name', 'middle_name', 'last_name', 'display_name', 'nickname', 'app_status', 'email', 'offer_data', 'background_data', 'signing_data', 'appeared', 'resume', 'id', 'date_create', 'user_create', 'upload'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Application $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addExam(\Hris\RecruitmentBundle\Entity\ApplicationExam $exam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExam', [$exam]);

        return parent::addExam($exam);
    }

    /**
     * {@inheritDoc}
     */
    public function getExam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExam', []);

        return parent::getExam();
    }

    /**
     * {@inheritDoc}
     */
    public function addInterview(\Hris\RecruitmentBundle\Entity\ApplicationInterview $interview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInterview', [$interview]);

        return parent::addInterview($interview);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterview', []);

        return parent::getInterview();
    }

    /**
     * {@inheritDoc}
     */
    public function addProfile(\Hris\RecruitmentBundle\Entity\ApplicationProfile $profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProfile', [$profile]);

        return parent::addProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function addEducation(\Hris\RecruitmentBundle\Entity\ApplicationEducation $education)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEducation', [$education]);

        return parent::addEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', []);

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function clearEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearEducation', []);

        return parent::clearEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function addExperience(\Hris\RecruitmentBundle\Entity\ApplicationExperience $experience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExperience', [$experience]);

        return parent::addExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function clearExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearExperience', []);

        return parent::clearExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function addSkills(\Hris\RecruitmentBundle\Entity\ApplicationSkills $skills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSkills', [$skills]);

        return parent::addSkills($skills);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkills', []);

        return parent::getSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function clearSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearSkills', []);

        return parent::clearSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function addReference(\Hris\RecruitmentBundle\Entity\ApplicationReference $reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReference', [$reference]);

        return parent::addReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function clearReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearReference', []);

        return parent::clearReference();
    }

    /**
     * {@inheritDoc}
     */
    public function addInformation(\Hris\RecruitmentBundle\Entity\ApplicationInformation $info)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInformation', [$info]);

        return parent::addInformation($info);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformation', []);

        return parent::getInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setChoice($choice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChoice', [$choice]);

        return parent::setChoice($choice);
    }

    /**
     * {@inheritDoc}
     */
    public function getChoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChoice', []);

        return parent::getChoice();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$name]);

        return parent::setFirstName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiddleName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiddleName', [$name]);

        return parent::setMiddleName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiddleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiddleName', []);

        return parent::getMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$name]);

        return parent::setLastName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', []);

        return parent::setDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', []);

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNickName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickName', [$name]);

        return parent::setNickName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function getNickname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickname', []);

        return parent::getNickname();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailAddress($eadd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailAddress', [$eadd]);

        return parent::setEmailAddress($eadd);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailAddress', []);

        return parent::getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setApplicationStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplicationStatus', [$status]);

        return parent::setApplicationStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicationStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplicationStatus', []);

        return parent::getApplicationStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobOffer($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobOffer', [$data]);

        return parent::setJobOffer($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobOffer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobOffer', []);

        return parent::getJobOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundCheck($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundCheck', [$data]);

        return parent::setBackgroundCheck($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundCheck()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundCheck', []);

        return parent::getBackgroundCheck();
    }

    /**
     * {@inheritDoc}
     */
    public function addChecklist(\Hris\RecruitmentBundle\Entity\ApplicationChecklist $checklist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChecklist', [$checklist]);

        return parent::addChecklist($checklist);
    }

    /**
     * {@inheritDoc}
     */
    public function getChecklist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChecklist', []);

        return parent::getChecklist();
    }

    /**
     * {@inheritDoc}
     */
    public function clearChecklist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearChecklist', []);

        return parent::clearChecklist();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractSigning($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractSigning', [$data]);

        return parent::setContractSigning($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractSigning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractSigning', []);

        return parent::getContractSigning();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppeared($appeared)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppeared', [$appeared]);

        return parent::setAppeared($appeared);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppeared()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppeared', []);

        return parent::getAppeared();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusFormatted', []);

        return parent::getStatusFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setResume($resume)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResume', [$resume]);

        return parent::setResume($resume);
    }

    /**
     * {@inheritDoc}
     */
    public function getResume()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResume', []);

        return parent::getResume();
    }

    /**
     * {@inheritDoc}
     */
    public function toData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toData', []);

        return parent::toData();
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function dataHasGeneratedID(&$data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataHasGeneratedID', [$data]);

        return parent::dataHasGeneratedID($data);
    }

    /**
     * {@inheritDoc}
     */
    public function initTrackCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initTrackCreate', []);

        return parent::initTrackCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreate(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreate', [$date]);

        return parent::setDateCreate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreate', []);

        return parent::getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreateFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreateFormatted', []);

        return parent::getDateCreateFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreate(\Quadrant\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreate', [$user]);

        return parent::setUserCreate($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreate', []);

        return parent::getUserCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function initIsUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initIsUpload', []);

        return parent::initIsUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpload(\Quadrant\MediaBundle\Entity\Upload $upload)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpload', [$upload]);

        return parent::setUpload($upload);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpload', []);

        return parent::getUpload();
    }

}
