<?php

namespace Proxies\__CG__\Hris\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Schedules extends \Hris\AdminBundle\Entity\Schedules implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'start', 'end', 'day_start', 'day_end', 'grace_period', 'half_day', 'type', 'required_hours', 'working_day', 'flag_deduction', 'minutes_deduction', 'color_code', 'minutes_deducted', 'minutes_added', 'reconsider_number', 'location', 'id', 'name', 'date_create', 'user_create'];
        }

        return ['__isInitialized__', 'start', 'end', 'day_start', 'day_end', 'grace_period', 'half_day', 'type', 'required_hours', 'working_day', 'flag_deduction', 'minutes_deduction', 'color_code', 'minutes_deducted', 'minutes_added', 'reconsider_number', 'location', 'id', 'name', 'date_create', 'user_create'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Schedules $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setStart(\DateTime $start)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStart', [$start]);

        return parent::setStart($start);
    }

    /**
     * {@inheritDoc}
     */
    public function getStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStart', []);

        return parent::getStart();
    }

    /**
     * {@inheritDoc}
     */
    public function getStartObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartObj', []);

        return parent::getStartObj();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnd(\DateTime $end)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnd', [$end]);

        return parent::setEnd($end);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchedHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchedHours', []);

        return parent::getSchedHours();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnd', []);

        return parent::getEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndObj', []);

        return parent::getEndObj();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayStart($start)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayStart', [$start]);

        return parent::setDayStart($start);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayStart', []);

        return parent::getDayStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayEnd($end)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayEnd', [$end]);

        return parent::setDayEnd($end);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayEnd', []);

        return parent::getDayEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplaySchedule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplaySchedule', []);

        return parent::getDisplaySchedule();
    }

    /**
     * {@inheritDoc}
     */
    public function setGracePeriod($grace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGracePeriod', [$grace]);

        return parent::setGracePeriod($grace);
    }

    /**
     * {@inheritDoc}
     */
    public function getGracePeriod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGracePeriod', []);

        return parent::getGracePeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function getGracePeriodText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGracePeriodText', []);

        return parent::getGracePeriodText();
    }

    /**
     * {@inheritDoc}
     */
    public function setHalfday($halfday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHalfday', [$halfday]);

        return parent::setHalfday($halfday);
    }

    /**
     * {@inheritDoc}
     */
    public function getHalfday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHalfday', []);

        return parent::getHalfday();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeLabel', []);

        return parent::getTypeLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequiredHours($required_hours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequiredHours', [$required_hours]);

        return parent::setRequiredHours($required_hours);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequiredHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequiredHours', []);

        return parent::getRequiredHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkingDays($working_day)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkingDays', [$working_day]);

        return parent::setWorkingDays($working_day);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDays', []);

        return parent::getWorkingDays();
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDaysFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDaysFormatted', []);

        return parent::getWorkingDaysFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinutesDeduction($minutes_deduction = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinutesDeduction', [$minutes_deduction]);

        return parent::setMinutesDeduction($minutes_deduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinutesDeduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinutesDeduction', []);

        return parent::getMinutesDeduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlagDeduction($flag_deduction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlagDeduction', [$flag_deduction]);

        return parent::setFlagDeduction($flag_deduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlagDeduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlagDeduction', []);

        return parent::getFlagDeduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setColorCode($color_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColorCode', [$color_code]);

        return parent::setColorCode($color_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getColorCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColorCode', []);

        return parent::getColorCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDaysNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDaysNum', []);

        return parent::getWorkingDaysNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDaysShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDaysShort', []);

        return parent::getWorkingDaysShort();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinutesToBeDeducted($minutes_deducted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinutesToBeDeducted', [$minutes_deducted]);

        return parent::setMinutesToBeDeducted($minutes_deducted);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinutesToBeDeducted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinutesToBeDeducted', []);

        return parent::getMinutesToBeDeducted();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinutesToBeAdded($minutes_added)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinutesToBeAdded', [$minutes_added]);

        return parent::setMinutesToBeAdded($minutes_added);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinutesToBeAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinutesToBeAdded', []);

        return parent::getMinutesToBeAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberOfReconsideration($reconsider_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberOfReconsideration', [$reconsider_number]);

        return parent::setNumberOfReconsideration($reconsider_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfReconsideration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfReconsideration', []);

        return parent::getNumberOfReconsideration();
    }

    /**
     * {@inheritDoc}
     */
    public function toData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toData', []);

        return parent::toData();
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function dataHasGeneratedID(&$data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataHasGeneratedID', [$data]);

        return parent::dataHasGeneratedID($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function initHasName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initHasName', []);

        return parent::initHasName();
    }

    /**
     * {@inheritDoc}
     */
    public function dataHasName(&$data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataHasName', [$data]);

        return parent::dataHasName($data);
    }

    /**
     * {@inheritDoc}
     */
    public function initTrackCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initTrackCreate', []);

        return parent::initTrackCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreate(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreate', [$date]);

        return parent::setDateCreate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreate', []);

        return parent::getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreateFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreateFormatted', []);

        return parent::getDateCreateFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreate(\Quadrant\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreate', [$user]);

        return parent::setUserCreate($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreate', []);

        return parent::getUserCreate();
    }

}
