<?php

namespace Proxies\__CG__\Hris\WorkforceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employee extends \Hris\WorkforceBundle\Entity\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'first_name', 'middle_name', 'last_name', 'gender', 'title', 'suffix', 'department', 'job_title', 'job_level', 'employment_status', 'location', 'attendance', 'transfer', 'schedule', 'sat_schedule', 'pay_period', 'deductable_rate', 'pay_rate', 'pay_earning_type', 'pay_sched', 'commission_pay_sched', 'allowance', 'profile', 'application_profile', 'user', 'enabled', 'has_account', 'email', 'corporation', 'division', 'contract_days', 'working_days', 'supervisor', 'subordinates', 'employee_code', 'date_hired', 'end_contract', 'date_separated', 'probation_month', 'marital_status', 'flag_new', 'dependents', 'exemption', 'income_tax', 'salary_history', 'employment_history', 'cashbond_rate', 'roles', 'payroll_type', 'display_name', 'reference', 'health_record', 'education', 'experience', 'information', 'memos', 'issued_property', 'contact_person', 'contact_number', 'cutoff_group', 'payroll_exemption', 'fix_payroll', 'id', 'date_create', 'user_create'];
        }

        return ['__isInitialized__', 'first_name', 'middle_name', 'last_name', 'gender', 'title', 'suffix', 'department', 'job_title', 'job_level', 'employment_status', 'location', 'attendance', 'transfer', 'schedule', 'sat_schedule', 'pay_period', 'deductable_rate', 'pay_rate', 'pay_earning_type', 'pay_sched', 'commission_pay_sched', 'allowance', 'profile', 'application_profile', 'user', 'enabled', 'has_account', 'email', 'corporation', 'division', 'contract_days', 'working_days', 'supervisor', 'subordinates', 'employee_code', 'date_hired', 'end_contract', 'date_separated', 'probation_month', 'marital_status', 'flag_new', 'dependents', 'exemption', 'income_tax', 'salary_history', 'employment_history', 'cashbond_rate', 'roles', 'payroll_type', 'display_name', 'reference', 'health_record', 'education', 'experience', 'information', 'memos', 'issued_property', 'contact_person', 'contact_number', 'cutoff_group', 'payroll_exemption', 'fix_payroll', 'id', 'date_create', 'user_create'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setApplication($application_profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplication', [$application_profile]);

        return parent::setApplication($application_profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplication', []);

        return parent::getApplication();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$name]);

        return parent::setFirstName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiddleName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiddleName', [$name]);

        return parent::setMiddleName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiddleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiddleName', []);

        return parent::getMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$name]);

        return parent::setLastName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuffix($suffix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuffix', [$suffix]);

        return parent::setSuffix($suffix);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuffix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuffix', []);

        return parent::getSuffix();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartment($department)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartment', [$department]);

        return parent::setDepartment($department);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartment', []);

        return parent::getDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartmentFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartmentFormatted', []);

        return parent::getDepartmentFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSchedule($schedule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSchedule', [$schedule]);

        return parent::setSchedule($schedule);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchedule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchedule', []);

        return parent::getSchedule();
    }

    /**
     * {@inheritDoc}
     */
    public function setSatSchedule($sat_schedule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSatSchedule', [$sat_schedule]);

        return parent::setSatSchedule($sat_schedule);
    }

    /**
     * {@inheritDoc}
     */
    public function getSatSchedule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSatSchedule', []);

        return parent::getSatSchedule();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmploymentStatus($employment_status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmploymentStatus', [$employment_status]);

        return parent::setEmploymentStatus($employment_status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmploymentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmploymentStatus', []);

        return parent::getEmploymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getLengthOfService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLengthOfService', []);

        return parent::getLengthOfService();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobTitle($job_title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobTitle', [$job_title]);

        return parent::setJobTitle($job_title);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobTitle', []);

        return parent::getJobTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractDays($contract_days)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractDays', [$contract_days]);

        return parent::setContractDays($contract_days);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractDays', []);

        return parent::getContractDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorkingDays($working_days)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorkingDays', [$working_days]);

        return parent::setWorkingDays($working_days);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkingDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkingDays', []);

        return parent::getWorkingDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobLevel($job_level)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobLevel', [$job_level]);

        return parent::setJobLevel($job_level);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobLevel', []);

        return parent::getJobLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$status]);

        return parent::setEnabled($status);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasAccount($has_account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasAccount', [$has_account]);

        return parent::setHasAccount($has_account);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasAccount', []);

        return parent::getHasAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorporation($corporation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorporation', [$corporation]);

        return parent::setCorporation($corporation);
    }

    /**
     * {@inheritDoc}
     */
    public function setDivision($division)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivision', [$division]);

        return parent::setDivision($division);
    }

    /**
     * {@inheritDoc}
     */
    public function getDivision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivision', []);

        return parent::getDivision();
    }

    /**
     * {@inheritDoc}
     */
    public function getCorporation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorporation', []);

        return parent::getCorporation();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile($profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile', [$profile]);

        return parent::setProfile($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile', []);

        return parent::getProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeId($employee_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeId', [$employee_code]);

        return parent::setEmployeeId($employee_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeId', []);

        return parent::getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupervisor($supervisor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupervisor', [$supervisor]);

        return parent::setSupervisor($supervisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupervisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupervisor', []);

        return parent::getSupervisor();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubordinates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubordinates', []);

        return parent::getSubordinates();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubordinateNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubordinateNames', []);

        return parent::getSubordinateNames();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', []);

        return parent::setDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', []);

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayNameMiddle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayNameMiddle', []);

        return parent::getDisplayNameMiddle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayPeriod($pay_period)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayPeriod', [$pay_period]);

        return parent::setPayPeriod($pay_period);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayPeriod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayPeriod', []);

        return parent::getPayPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayEarningType($pay_earning_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayEarningType', [$pay_earning_type]);

        return parent::setPayEarningType($pay_earning_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayEarningType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayEarningType', []);

        return parent::getPayEarningType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaySchedule($pay_sched)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaySchedule', [$pay_sched]);

        return parent::setPaySchedule($pay_sched);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaySchedule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaySchedule', []);

        return parent::getPaySchedule();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommissionPaySchedule($commission_pay_sched)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommissionPaySchedule', [$commission_pay_sched]);

        return parent::setCommissionPaySchedule($commission_pay_sched);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommissionPaySchedule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommissionPaySchedule', []);

        return parent::getCommissionPaySchedule();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayRate($pay_rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayRate', [$pay_rate]);

        return parent::setPayRate($pay_rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayRate', []);

        return parent::getPayRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeductableRate($deductable_rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeductableRate', [$deductable_rate]);

        return parent::setDeductableRate($deductable_rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeductableRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeductableRate', []);

        return parent::getDeductableRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateHired($date_hired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateHired', [$date_hired]);

        return parent::setDateHired($date_hired);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateHired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateHired', []);

        return parent::getDateHired();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateHiredFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateHiredFormatted', []);

        return parent::getDateHiredFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndContract($end_contract)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndContract', [$end_contract]);

        return parent::setEndContract($end_contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndContract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndContract', []);

        return parent::getEndContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSeparated($date_separated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSeparated', [$date_separated]);

        return parent::setDateSeparated($date_separated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSeparated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSeparated', []);

        return parent::getDateSeparated();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSeparatedFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSeparatedFormatted', []);

        return parent::getDateSeparatedFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndContractFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndContractFormatted', []);

        return parent::getEndContractFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setProbationMonth($probation_month)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProbationMonth', [$probation_month]);

        return parent::setProbationMonth($probation_month);
    }

    /**
     * {@inheritDoc}
     */
    public function getProbationMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbationMonth', []);

        return parent::getProbationMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function getProbationMonthFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProbationMonthFormatted', []);

        return parent::getProbationMonthFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttendance($attendance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttendance', [$attendance]);

        return parent::setAttendance($attendance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendance', []);

        return parent::getAttendance();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaritalStatus($marital_status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaritalStatus', [$marital_status]);

        return parent::setMaritalStatus($marital_status);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaritalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaritalStatus', []);

        return parent::getMaritalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDependents($dependent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDependents', [$dependent]);

        return parent::setDependents($dependent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependents', []);

        return parent::getDependents();
    }

    /**
     * {@inheritDoc}
     */
    public function getQualifiedDependents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualifiedDependents', []);

        return parent::getQualifiedDependents();
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', []);

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setOld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOld', []);

        return parent::setOld();
    }

    /**
     * {@inheritDoc}
     */
    public function isExempted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExempted', []);

        return parent::isExempted();
    }

    /**
     * {@inheritDoc}
     */
    public function setExemption($exemption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExemption', [$exemption]);

        return parent::setExemption($exemption);
    }

    /**
     * {@inheritDoc}
     */
    public function isIncomeTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIncomeTax', []);

        return parent::isIncomeTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncomeTax($income_tax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncomeTax', [$income_tax]);

        return parent::setIncomeTax($income_tax);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonthlyRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonthlyRate', []);

        return parent::getMonthlyRate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDailyRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDailyRate', []);

        return parent::getDailyRate();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaryHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaryHistory', []);

        return parent::getSalaryHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashbondRate($rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashbondRate', [$rate]);

        return parent::setCashbondRate($rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashbondRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashbondRate', []);

        return parent::getCashbondRate();
    }

    /**
     * {@inheritDoc}
     */
    public function getRateforPeriod($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateforPeriod', [$date]);

        return parent::getRateforPeriod($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowance($allowance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowance', [$allowance]);

        return parent::setAllowance($allowance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowance', []);

        return parent::getAllowance();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayrollType($payroll_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayrollType', [$payroll_type]);

        return parent::setPayrollType($payroll_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayrollType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayrollType', []);

        return parent::getPayrollType();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$group]);

        return parent::addRole($group);
    }

    /**
     * {@inheritDoc}
     */
    public function clearRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearRoles', []);

        return parent::clearRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getRolesText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolesText', []);

        return parent::getRolesText();
    }

    /**
     * {@inheritDoc}
     */
    public function getRolesID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolesID', []);

        return parent::getRolesID();
    }

    /**
     * {@inheritDoc}
     */
    public function isUserRole($groupName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUserRole', [$groupName]);

        return parent::isUserRole($groupName);
    }

    /**
     * {@inheritDoc}
     */
    public function hasAccess($acl_key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAccess', [$acl_key]);

        return parent::hasAccess($acl_key);
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setHealthRecord($health_record)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHealthRecord', [$health_record]);

        return parent::setHealthRecord($health_record);
    }

    /**
     * {@inheritDoc}
     */
    public function getHealthRecord()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHealthRecord', []);

        return parent::getHealthRecord();
    }

    /**
     * {@inheritDoc}
     */
    public function addReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReference', [$reference]);

        return parent::addReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function clearReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearReference', []);

        return parent::clearReference();
    }

    /**
     * {@inheritDoc}
     */
    public function addEducation($education)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEducation', [$education]);

        return parent::addEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', []);

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function clearEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearEducation', []);

        return parent::clearEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function addExperience($experience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExperience', [$experience]);

        return parent::addExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function clearExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearExperience', []);

        return parent::clearExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function addInformation($info)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInformation', [$info]);

        return parent::addInformation($info);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformation', []);

        return parent::getInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function getIssuedProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssuedProperties', []);

        return parent::getIssuedProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function getMemos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMemos', []);

        return parent::getMemos();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPerson($contact_person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPerson', [$contact_person]);

        return parent::setContactPerson($contact_person);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPerson', []);

        return parent::getContactPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactNumber($contact_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactNumber', [$contact_number]);

        return parent::setContactNumber($contact_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactNumber', []);

        return parent::getContactNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCutoffGroup($cutoff_group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCutoffGroup', [$cutoff_group]);

        return parent::setCutoffGroup($cutoff_group);
    }

    /**
     * {@inheritDoc}
     */
    public function getCutoffGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCutoffGroup', []);

        return parent::getCutoffGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function isPayrollExempted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPayrollExempted', []);

        return parent::isPayrollExempted();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixPayroll($fix_payroll)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixPayroll', [$fix_payroll]);

        return parent::setFixPayroll($fix_payroll);
    }

    /**
     * {@inheritDoc}
     */
    public function isFixPayroll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFixPayroll', []);

        return parent::isFixPayroll();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayrollExemption($payroll_exemption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayrollExemption', [$payroll_exemption]);

        return parent::setPayrollExemption($payroll_exemption);
    }

    /**
     * {@inheritDoc}
     */
    public function toData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toData', []);

        return parent::toData();
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function dataHasGeneratedID(&$data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dataHasGeneratedID', [$data]);

        return parent::dataHasGeneratedID($data);
    }

    /**
     * {@inheritDoc}
     */
    public function initTrackCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initTrackCreate', []);

        return parent::initTrackCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreate(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreate', [$date]);

        return parent::setDateCreate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreate', []);

        return parent::getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreateFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreateFormatted', []);

        return parent::getDateCreateFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreate(\Quadrant\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreate', [$user]);

        return parent::setUserCreate($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreate', []);

        return parent::getUserCreate();
    }

}
