
hris_tools_bonus_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:BonusFine:index }

hris_tools_bonus_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:BonusFine:grid }

hris_tools_bonus_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:BonusFine:addForm }

hris_tools_bonus_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: HrisToolsBundle:BonusFine:addSubmit }

hris_tools_bonus_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:BonusFine:editForm }

hris_tools_bonus_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: HrisToolsBundle:BonusFine:editSubmit }

hris_tools_bonus_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:BonusFine:delete }


hris_tools_bonus_csv:
    pattern: /csv
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:BonusFine:csv }


