
hris_tools_deposit_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:Deposit:index }

hris_tools_deposit_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:Deposit:grid }

hris_tools_deposit_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:Deposit:addForm }

hris_tools_deposit_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: HrisToolsBundle:Deposit:addSubmit }

hris_tools_deposit_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:Deposit:editForm }

hris_tools_deposit_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: HrisToolsBundle:Deposit:editSubmit }

hris_tools_deposit_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:Deposit:delete }

hris_tools_deposit_csv:
    pattern: /csv
    methods: [GET]
    defaults: { _controller: HrisToolsBundle:Deposit:csv }
